version: '3.8'

services:
  iproj-web:
    image: iproj-web-image   
    build:
      context: .
      dockerfile: ./src/IProj.Web/Dockerfile
    container_name: iproj-web
    ports:
      - "4040:8080"
      - "8081:8081"
    networks:
      - iproj-network
    restart: always          

  iproj-consumer:
    image: iproj-consumer-image
    build:
      context: .
      dockerfile: ./src/IProj.Consumer/Dockerfile
    container_name: iproj-consumer
    ports:
      - "8090:8080"
      - "8091:8081"
    networks:
      - iproj-network 
    restart: always      

  iproj-admin:
    image: iproj-admin-image  
    build:
      context: .
      dockerfile: ./src/IProjAdmin.Web/Dockerfile
    container_name: iproj-admin
    ports:
      - "6060:8080"         
    networks:
      - iproj-network
    restart: always      

networks:
  iproj-network:
    driver: bridge
